name: ustreamer
version: '5.41'
summary: Lightweight and fast MJPEG-HTTP streamer
description: |
  µStreamer is a lightweight and very quick server to stream MJPEG video from any V4L2 device to the net.
  All new browsers have native support of this video format, as well as most video players such as mplayer, VLC etc.
  µStreamer is a part of the PiKVM project designed to stream VGA and HDMI screencast hardware data with the highest
  resolution and FPS possible.

base: core22
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  ustreamer:
    source: https://github.com/pikvm/ustreamer.git
    source-type: git
    source-depth: 1
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    plugin: make
    build-packages:
      - build-essential
    stage-packages:
      - libjpeg-dev
      - libbsd-dev
      - libevent-dev

apps:
  ustreamer:
    command: usr/local/bin/ustreamer
