name: ustreamer
adopt-info: ustreamer
summary: Lightweight and fast MJPEG-HTTP streamer
description: |
  µStreamer is a lightweight and very quick server to stream MJPEG video from any V4L2 device to the net.
  All new browsers have native support of this video format, as well as most video players such as mplayer, VLC etc.
  µStreamer is a part of the PiKVM project designed to stream VGA and HDMI screencast hardware data with the highest
  resolution and FPS possible.

base: core22
confinement: strict

parts:
  ustreamer:
    source: https://github.com/pikvm/ustreamer.git
    source-type: git
    source-depth: 1
    source-tag: v5.41
    plugin: make
    build-packages:
      - build-essential
    stage-packages:
      - libjpeg-dev
      - libbsd-dev
      - libevent-dev
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags | sed 's/v//')

apps:
  ustreamer:
    command: usr/local/bin/ustreamer
    plugs:
      - network-bind
      - camera
